export const SET_HEIGHT = 'SWET_HEIGHT';
export const SET_WIDTH = 'SET_WIDTH';
export const SET_BORDERRADIUS = 'SET_BORDERRADIUS';
export const SET_BORDERRADIUS_TOPLEFT = 'SET_BORDERRADIUS_TOPLEFT';
export const SET_BORDERRADIUS_TOPRIGHT = 'SET_BORDERRADIUS_TOPRIGHT';
export const SET_BORDERRADIUS_BOTTOMRIGHT = 'SET_BORDERRADIUS_BOTTOMRIGHT';
export const SET_BORDERRADIUS_BOTTOMLEFT = 'SET_BORDERRADIUS_BOTTOMLEFT';
export const SET_TEXTSIZE = 'SET_TEXTSIZE';
