export const SET_HEIGHT = 'SWET_HEIGHT';
export const SET_WIDTH = 'SET_WIDTH';

export const SET_BACKGROUNDCOLOR = 'SET_BACKGROUNDCOLOR';
export const SET_COLOR = 'SET_COLOR';

export const SET_BORDER = 'SET_BORDER';
export const SET_BORDERSTYLE = 'SET_BORDERSTYLE';

export const SET_BORDERWIDTH = 'SET_BORDERWIDTH';
export const SET_BORDERWIDTH_TOP = 'SET_BORDERWIDTH_TOP';
export const SET_BORDERWIDTH_RIGHT = 'SET_BORDERWIDTH_RIGHT';
export const SET_BORDERWIDTH_BOTTOM = 'SET_BORDERWIDTH_BOTTOM';
export const SET_BORDERWIDTH_LEFT = 'SET_BORDERWIDTH_LEFT';

export const SET_BORDERCOLOR = 'SET_BORDERCOLOR';
export const SET_BORDERRADIUS = 'SET_BORDERRADIUS';
export const SET_BORDERRADIUS_TOPLEFT = 'SET_BORDERRADIUS_TOPLEFT';
export const SET_BORDERRADIUS_TOPRIGHT = 'SET_BORDERRADIUS_TOPRIGHT';
export const SET_BORDERRADIUS_BOTTOMRIGHT = 'SET_BORDERRADIUS_BOTTOMRIGHT';
export const SET_BORDERRADIUS_BOTTOMLEFT = 'SET_BORDERRADIUS_BOTTOMLEFT';

export const SET_MARGIN = 'SET_MARGIN';
export const SET_MARGIN_TOP = 'SET_MARGIN_TOP';
export const SET_MARGIN_RIGHT = 'SET_MARGIN_RIGHT';
export const SET_MARGIN_BOTTOM = 'SET_MARGIN_BOTTOM';
export const SET_MARGIN_LEFT = 'SET_MARGIN_LEFT';

export const SET_PADDING = 'SET_PADDING';
export const SET_PADDING_TOP = 'SET_PADDING_TOP';
export const SET_PADDING_RIGHT = 'SET_PADDING_RIGHT';
export const SET_PADDING_BOTTOM = 'SET_PADDING_BOTTOM';
export const SET_PADDING_LEFT = 'SET_PADDING_LEFT';

export const SET_FONTSIZE = 'SET_FONTSIZE';
export const SET_TEXT = 'SET_TEXT';
